<?php
$output .= "<div id='ef-dialog' title='" . __('Login') . "'>";
$output .= "	<form id='ef-dialog-form' class='ef-form' name='ef-dialog-form' method='post' action='" . current_page_url() . "'>";
$output .= "		<input type='hidden' name='action' value='dialog-post'>";
$output .= "		<fieldset>";
$output .= "			<div class='ef-form-group'>";
$output .= "				<label class='ef-form-label' for='ef-login'>" . __('Username:') . "</label>";
$output .= "				<div class='ef-form-control'>";
$output .= "					<input type='text' name='ef-login' id='ef-login' value='" . $_POST['ef-login'] . "' />";
$output .= "				</div>";
$output .= "			</div>";
$output .= "			<div class='ef-form-group'>";
$output .= "				<label class='ef-form-label' for='ef-password'>" . __('Password:') . "</label>";
$output .= "				<div class='ef-form-control'>";
$output .= "					<input type='password' name='ef-password' id='ef-password' value='" . $_POST['ef-password'] . "' />";
$output .= "				</div>";
$output .= "			</div>";
$output .= "		</fieldset>";
$output .= "	</form>";
$output .= "</div>";

$output .= "<script type='text/javascript'>";
$output .= "	jQuery(document).ready(function() {";
$output .= "		jQuery('#ef-dialog').dialog({";
$output .= "			width : 350,";
$output .= "			modal : true,";
$output .= "			autoOpen : false,";
$output .= "			buttons : {";
$output .= "				'Login' : function() {";
$output .= "					jQuery('#ef-dialog-form').submit();";
$output .= "				},";
$output .= "				Cancel : function() {";
$output .= "					jQuery(this).dialog('close');";
$output .= "				}";
$output .= "			},";
$output .= "		});";
$output .= "	});";
$output .= "	jQuery('#ef-dialog-open').click(function() {";
$output .= "		jQuery('#ef-dialog').dialog('open');";
$output .= "		return false;";
$output .= "	});";
$output .= "</script>";